### PR TITLE
new futur combinator suggestion #firstSuccessfulCompleteOf:.

### PR DESCRIPTION
**Pull request by mattonem**
Hello guys, 
Could you please consider this contribution ? or just discuss about my usecase...

My usecase:
- I have to decrypt some data that might have been encrypted using different (known) private keys.
- I have up to 100 possible keys.
- The decryption service is a microservice somewhere.
- I want to send all decryption requests at the same time and get the first successful one. 

I think this #firstSucccessfulCompleteOf: is a cool addiction to taskIt futur combinators and could come handy in other usecases.

Although the error handling I implemented is terrible... 

Please let me know what you think about it.

regards 
max

### CODE REVIEW

**Comment by tinchodias** [comment]
Oh, too bad we didn't review this before... Sorry @mattonem, I didn't analyze the codes but I think @noha already covered this functionality with `TKTFuture>>any:` in https://github.com/pharo-contributions/taskit/pull/80. I'd be great if you can check if I'm right. Maybe there is something to complement.

**Comment by tinchodias** [comment]
Here: https://github.com/pharo-contributions/taskit/pull/80/files#diff-8a7acf4d9ac8027daae12831367f8ddad36a5518c4d00c5176bf218b8f0ee32bR180

**Comment by tinchodias** [comment]
I looked again with more detail and I think it can be valuable to have both. Norbert's `any:` is class side and receives a collection of futures, while @mattonem's `firstSucccessfulCompleteOf:` is instance-side, of self "against" another received as argument.

**Comment by mattonem** [comment]
Thanks @tinchodias. It was a while ago so I don't remember the exact details of the contribution... But I think the error handling was pretty bad... I'll take a look at @noha contribution and align on how ever he implemented it.

**Comment by mattonem** [comment]
Btw behaviour of `any:` is not exactly the same as it would return the first future to finish. The purpose of `firstSuccesfulCompleteOf:` is also to ignore failure and the futures running until a success pop's up.

**Comment by mattonem** [comment]
Now we could also consider implementing a class side method `anySucessful:`. Would that be useful?

**Comment by noha** [comment]
Looking at it again the implementation of any is wrong. Any is supposed to succeed on first success of any future and fail only if all failed. I can correct this

**Comment by noha** [comment]
I corrected the any future. Have a look at #104

**Comment by noha** [comment]
Btw. what is the difference between this and firstCompleteOf: ?

**Comment by mattonem** [comment]
> Btw. what is the difference between this and firstCompleteOf: ?

`firstCompleteOf:` will stop at failure, return the failure, and freeze the other futur...

**Pull request merged**
